"""Declarative base and shared column conventions."""

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import JSON, Enum, MetaData, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit constraint names. Without them SQLite generates anonymous
# constraints that Alembic cannot address when rewriting a table, which is how
# every migration on SQLite works.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def utcnow() -> datetime:
    """Timezone-aware current time.

    Defaults are applied in Python rather than by the database: SQLite and
    PostgreSQL disagree on what `CURRENT_TIMESTAMP` returns and whether it
    carries a timezone.
    """
    return datetime.now(UTC)


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key column, UUID on PostgreSQL and CHAR(32) on SQLite."""
    return mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


def enum_column(enum_class: type[StrEnum], name: str) -> Enum:
    """String column with a check constraint, not a native database enum.

    `create_constraint` has defaulted to False since SQLAlchemy 1.4, so
    without it the column is a plain VARCHAR that accepts anything the ORM
    did not happen to validate.

    `values_callable` stores the member values (`"in_review"`) rather than the
    member names (`"IN_REVIEW"`), so the database holds what the API speaks.
    """
    return Enum(
        enum_class,
        name=name,
        native_enum=False,
        create_constraint=True,
        validate_strings=True,
        values_callable=lambda enum: [member.value for member in enum],
    )


def json_type() -> JSON:
    """A fresh JSON type instance, plain JSON on both backends.

    Must be called per column rather than shared: `MutableDict.as_mutable()`
    and `MutableList.as_mutable()` register their coercion on the type
    *instance*, so one shared instance makes the last registration win and the
    other column reject its own values.

    PostgreSQL's JSONB would be the better storage — it can be indexed — but a
    dialect variant renders into migrations as `postgresql.JSONB(astext_type=
    Text())`, a name the migration does not import, so autogenerated migrations
    fail on the second table that uses it. Nothing queries inside these columns
    in v1.0: custom fields arrive with v2.0, and switching the column type is a
    migration of its own when that happens.
    """
    return JSON()
