"""term search text

Revision ID: a46f32d215e7
Revises: 91ef75070951
Create Date: 2026-08-03 12:16:04.630289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46f32d215e7'
down_revision: Union[str, Sequence[str], None] = '91ef75070951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_text', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_entries', schema=None) as batch_op:
        batch_op.drop_column('search_text')

    # ### end Alembic commands ###
