"""initial schema

Revision ID: e387f6c737bc
Revises: 
Create Date: 2026-08-03 10:40:51.675591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e387f6c737bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domains')),
    sa.UniqueConstraint('name', name=op.f('uq_domains_name'))
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(code) = 2', name=op.f('ck_languages_code_is_two_letters')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_languages'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'contributor', 'editor', 'reviewer', 'approver', 'admin', name='role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspace_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_workspace_settings_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_settings'))
    )
    op.create_table('change_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('concept', 'term_entry', name='history_entity_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_change_history_changed_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_history'))
    )
    with op.batch_alter_table('change_history', schema=None) as batch_op:
        batch_op.create_index('ix_change_history_entity', ['entity_type', 'entity_id', 'changed_at'], unique=False)

    op.create_table('concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lifecycle', sa.Enum('active', 'deprecated', name='concept_lifecycle', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.CheckConstraint("superseded_by_id IS NULL OR lifecycle = 'deprecated'", name=op.f('ck_concepts_successor_requires_deprecated')),
    sa.CheckConstraint('superseded_by_id IS NULL OR superseded_by_id <> id', name=op.f('ck_concepts_no_self_successor')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_concepts_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['concepts.id'], name=op.f('fk_concepts_superseded_by_id_concepts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts'))
    )
    op.create_table('concept_domains',
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_concept_domains_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_concept_domains_domain_id_domains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'domain_id', name=op.f('pk_concept_domains'))
    )
    op.create_table('term_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('nogo_alternatives', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('context_example', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'proposed', 'in_review', 'approved', 'rejected', name='term_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.Enum('manual', 'ai', 'import', name='entry_origin', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_term_entries_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_term_entries_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_term_entries_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_term_entries_language_code_languages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_entries')),
    sa.UniqueConstraint('concept_id', 'language_code', name='one_entry_per_language')
    )
    with op.batch_alter_table('term_entries', schema=None) as batch_op:
        batch_op.create_index('ix_term_entries_assignee_id', ['assignee_id'], unique=False)
        batch_op.create_index('ix_term_entries_status_language', ['status', 'language_code'], unique=False)

    op.create_table('review_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_entry_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('transition', sa.Enum('submitted', 'changes_requested', 'approved', 'rejected', name='review_transition', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_review_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_entry_id'], ['term_entries.id'], name=op.f('fk_review_comments_term_entry_id_term_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.create_index('ix_review_comments_term_entry_id_created_at', ['term_entry_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_review_comments_term_entry_id_created_at')

    op.drop_table('review_comments')
    with op.batch_alter_table('term_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_term_entries_status_language')
        batch_op.drop_index('ix_term_entries_assignee_id')

    op.drop_table('term_entries')
    op.drop_table('concept_domains')
    op.drop_table('concepts')
    with op.batch_alter_table('change_history', schema=None) as batch_op:
        batch_op.drop_index('ix_change_history_entity')

    op.drop_table('change_history')
    op.drop_table('workspace_settings')
    op.drop_table('users')
    op.drop_table('languages')
    op.drop_table('domains')
    # ### end Alembic commands ###
